### PR TITLE
Feature/83 - Graph Viewer Layout Improvements

### PR DESCRIPTION
**Pull request by jrmartin**

### CODE REVIEW

**Review by zsinnema — APPROVED** [review]

**Comment by ddelpiano** [comment]
@zsinnema @jrmartin if you are ok I can absorb this into feature/17 since I already resolved the conflict above, let me know if that is ok. Thx

**Comment by jrmartin** [comment]
@ddelpiano Good for me. Thanks!

**Comment by zsinnema** [comment]
@ddelpiano good for me too

**Comment by jrmartin** [comment]
Closing as it was absorbed by feature/17

**Pull request closed without merging**
