### PR TITLE
Feature/48 - Graph Viewer Component

### PR DESCRIPTION
**Pull request by jrmartin**
Create basic structure component for the Graph Viewer #48. 

#54 Will be implementing the controls for the Graph Viewer.

### CODE REVIEW

**Comment by jrmartin** [comment]
@zsinnema @vidhya-metacell There's an issue with the versions of react used by the graph-visualization ( version 16) component and the one used in sds viewer (version 17). 

This is the same issue we are having https://github.com/facebook/react/issues/20131. 

Downgraded to react 16.14 in SDS viewer and works, since alternative is to wait for the vasturiano graph library to upgrade to react 17.  

Bug with react 17: 
image

**Comment by vidhya-metacell** [comment]
@jrmartin I cannot see the graph, i see a component with controls but not a graph.
graph

**Comment by zsinnema** [comment]
I also saw that, Dario is looking at it right now and merging it with his code. @vidhya-metacell please contact @ddelpiano

**Comment by ddelpiano** [comment]
brought this inside feature/51

**Pull request closed without merging**
